function interp_method = fcn_DataClean_determineInterpolateMethod(field_name)


% fields_names=["GPS_Time",...
%         "Trigger_Time",...
%         "ROS_Time",...
%         "centiSeconds",...
%         "Npoints",...
%         "MessageID",...
%         "Latitude",...
%         "StdLat",...
%         "Longitude",...
%         "StdLon",...
%         "Altitude",...
%         "StdAlt",...
%         "GeoSep",...
%         "xEast",...
%         "yNorth",...
%         "zUp",...
%         "velNorth",...
%         "velEast",...
%         "velUp",...
%         "velMagnitude",...
%         "numSatellites",...
%         "DGPS_mode",...
%         "Roll_deg",...
%         "Pitch_deg",...
%         "Yaw_deg",...
%         "OneSigmaPos",...
%         "HDOP",...
%         "AgeOfDiff",...
%         "StdDevResid",...
%         "SpdOverGrndKmph",...
%         "TrueTrack",...
%         "GPS_EventFunctions",...
%         "ROS_Time2",...
%         "ROS_Time3",...
%         "Npoints3"];

fields_names=["ROS_Time",...
            "StdLat",...
            "StdLon",...
            "StdAlt",...
            "GeoSep",...
            "numSatellites",...
            "DGPS_mode",...
            "HDOP",...
            "AgeOfDiff",...
            "SpdOverGrndKmph",...
            "GPS_Time2",...
            "ROS_Time2",...
            "ROS_Time3"];

interp_methods = [1,1,1,1,0,0,0,0,0,1,1,1,1];

d = dictionary(fields_names,interp_methods);
interp_method_number = d(field_name);

if interp_method_number == 0
    interp_method = 'nearest';

elseif interp_method_number == 1
    interp_method = 'linear';

end